defaults:
 - dataset: pushT

reload_checkpoint: null
output_dir: /home/mim-server/projects/rooholla/dreamer-v4/dynamics_ckpts/${now:%Y-%m-%d_%H-%M-%S}
plot_every: 1000
print_every: 100
log_every: 25

denoiser:
  num_action_tokens: 2    # Number of tokens for the image or other modalities
  num_latent_tokens: 256      # The number of latent tokens per frame
  num_register_tokens: 8
  max_context_length: 64      # The maximum temporal horizon of the tokenizer
  model_dim: 768              # The dimension of the transformer latents
  latent_dim: 32              # The dimention of the encoder output latents (z)
  n_layers: 4           # Causal tokenizer encoder depth
  n_heads: 12
  n_kv_heads: 12
  dropout_prob: 0.0
  qk_norm: false
  K_max: 64
  n_discrete_actions: 0
  n_continuous_actions: 2
  discrete_action_bins: []

train:
  device: 'cuda:0'
  num_epochs: 100
  batch_size: 16
  short_context: 32
  long_context: 96
  accum_grad_steps: 1
  lr: 1e-4
  num_workers: 12
  lpips_weight: 0.2
  num_training_steps: 1e7
  mixed_precision: false
  torch_compile_mode: "default"
  enable_flash_attention: false
  enable_fast_matmul: true
  clip_grad_norm: 1.0

wandb:
  enable: true
  project: "dreamer-v4-dynamics"
  run_name: "debug-small-env"