defaults:
 - dataset: pushT

tokenizer:
  num_modality_tokens: 256 # Number of tokens for the image or other modalities
  num_latent_tokens: 512    # The number of latent tokens per frame
  max_context_length: 192  # The maximum temporal horizon of the tokenizer
  model_dim: 768          # The dimension of the transformer latents
  latent_dim: 16          # The dimention of the encoder output latents (z)
  enc_num_layers: 4        # Causal tokenizer encoder depth
  dec_num_layers: 4        # Causal tokenizer decoder depth
  n_heads: 8
  n_kv_heads: 8
  dropout_prob: 0.0
  qk_norm: true
  patch_size: 14

train:
  output_dir: checkpoints
  batch_size: 1
  accum_grad_steps: 1
  lr: 1e-4
  num_workers: 32
  evaluate_every: 5000
  save_every: 20000
  plots_every: 20000
  lpips_weight: 0.2
  num_training_steps: 1e7


wandb:
  enabled: false # Enable or disable wandb logging
  project: "dreamerv4-tokenizer" # Replace with your wandb project name

