dt: 0.2
resolution: [224, 224]
load_to_ram: false
base_path: /home/mim-server/datasets/pushT/224
train_sequences:
  - "episode_0.h5"
  - "episode_1.h5"
  - "episode_2.h5"
  - "episode_3.h5"
  - "episode_4.h5"
  - "episode_5.h5"
  - "episode_6.h5"
  - "episode_7.h5"
  - "episode_8.h5"
  - "episode_9.h5"
  - "episode_10.h5"

test_sequences:
  - "episode_11.h5"
  - "episode_12.h5"
